export const PRODUCT_REQUEST = "PRODUCT_REQUEST";
export const PRODUCT_FAILURE = "PRODUCT_FAILURE";
export const PRODUCT_SUCCESS = "PRODUCT_SUCCESS";

export const PRODUCT_DETAILS_REQUEST = "PRODUCT_DETAILS_REQUEST";
export const PRODUCT_DETAILS_FAILURE = "PRODUCT_DETAILS_FAILURE";
export const PRODUCT_DETAILS_SUCCESS = "PRODUCT_DETAILS_SUCCESS";
